navikt/ishuskelapp

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
- src/main/kotlin/no/nav/syfo/application/kafka/KafkaEnvironment.kt
- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
- src/main/kotlin/no/nav/syfo/huskelapp/kafka/HuskelappProducer.kt
- src/main/kotlin/no/nav/syfo/huskelapp/kafka/KafkaHuskelapp.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Oppretter kafka producer for huskelapp. Skal brukes i cronjob for å publisere huskelapper slik at ispersonoppgave kan lage oppgave til veileder.
> IS-1642: Create huskelapp kafka producer

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/BackgroundTask.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/Cronjob.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobResult.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobRunner.kt
- src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodClient.kt
- src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodDTO.kt
- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
- src/main/kotlin/no/nav/syfo/huskelapp/cronjob/PublishHuskelappCronjob.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Setter opp cronjob for å publisere huskelapper slik at ispersonoppgave kan lage oppgave. Publiserer foreløpig ingenting - implementer service-metoder for å finne upubliserte huskelapper osv i ny PR.
> IS-1642: Setup publish huskelapp cronjob

- src/main/kotlin/no/nav/syfo/huskelapp/api/HuskelappApi.kt
- src/main/kotlin/no/nav/syfo/huskelapp/api/HuskelappDTO.kt
- src/main/kotlin/no/nav/syfo/huskelapp/database/HuskelappRepository.kt
- src/main/kotlin/no/nav/syfo/huskelapp/database/PHuskelapp.kt
- src/main/kotlin/no/nav/syfo/huskelapp/domain/Huskelapp.kt
- src/main/kotlin/no/nav/syfo/huskelapp/kafka/HuskelappProducer.kt
- src/test/kotlin/no/nav/syfo/huskelapp/api/HuskelappApiSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/cronjob/PublishHuskelappCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/domain/HuskelappSpek.kt
Tar i bruk ny kolonne lagt til i https://github.com/navikt/ishuskelapp/pull/15 og implementer remove-funksjon på huskelapp.
Tar i bruk fra APIet i neste PR.
> IS-1656: Implement remove huskelapp

- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
- src/test/kotlin/no/nav/syfo/huskelapp/api/HuskelappApiSpek.kt
Avoid storing new version if text is unchanged
> No duplicates

- .github/pull_request_template.md
- src/main/kotlin/no/nav/syfo/application/metric/Metric.kt
- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
Bare et forslag til metrics vi kan telle og vise i grafana. Gir disse mening, eller er det andre ting vi heller vil se på? Normalt sett teller vi kanskje i consumers/producers og ikke i servicen.
> IS: Add metrics for huskelapp

- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
Når man kaller `huskelappRepository.create()` så lager man både en huskelapp og en versjon, glemte å ta med dette i forrige PR.
> IS: Add counter for Versjon when huskelapp is created

- src/main/kotlin/no/nav/syfo/huskelapp/api/HuskelappApi.kt
- src/main/kotlin/no/nav/syfo/huskelapp/api/HuskelappDTO.kt
Se https://github.com/navikt/syfomodiaperson/pull/1119
Vi vil heller sende LocalDateTime her, så det blir riktig klokkeslett i APIet. Dette kan vi da ta inn i frontenden.
> IS-1742: Add createdAt field in DTO, and send as LocalDateTime

- build.gradle.kts
> Upgrade deps

- build.gradle.kts
Hva er nytt / hva har blitt fikset?
> Bump postgres

- src/main/kotlin/no/nav/syfo/huskelapp/HuskelappService.kt
- src/main/kotlin/no/nav/syfo/huskelapp/cronjob/PublishHuskelappCronjob.kt
- src/main/kotlin/no/nav/syfo/huskelapp/database/HuskelappRepository.kt
- src/main/kotlin/no/nav/syfo/huskelapp/domain/Huskelapp.kt
- src/test/kotlin/no/nav/syfo/application/HuskelappServiceSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/cronjob/PublishHuskelappCronjobSpek.kt
Setter `published_at` til `null` ved endring av huskelapp slik at endringen blir publisert til `syfooversiktsrv`
> IS-2215: Set huskelapp unpublished on edit

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Ønsker å følge med på bulk-kallene. Kan se de fra `syfooversiktsrv` i dag, men ikke detaljene.
> IS: Add auto instrumentation

- .github/dependabot.yaml
- build.gradle.kts
- src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
For at dependabot skal finne gradle-dependenciene våre
> Upgrade dependencies and allow for dependabot scraping

- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/OppfolgingsoppgaveRepository.kt
Bruker `ANY`-keywordet slik Geir gjorde i `isarbeidsuforhet`, satser på at det hjelper 🤞🏼
> IS-2465: Get all oppfolgingsoppgaver in one db-query

- src/main/kotlin/no/nav/syfo/api/endpoints/OppfolgingsoppgaveApi.kt
- src/main/kotlin/no/nav/syfo/application/OppfolgingsoppgaveService.kt
- src/test/kotlin/no/nav/syfo/application/OppfolgingsoppgaveServiceSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/api/OppfolgingsoppgaveApiSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/cronjob/PublishOppfolgingsoppgaveCronjobSpek.kt
Oppdaget i forrige PR at DTOen var i bruk i servicen. Vil man helst unngå det, eller går det greit?
> Refactor: Dont use Api-DTO in service

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
> IS: Update db tier

- .nais/naiserator-dev.yaml
This reverts commit f1eecf50483ff2bd0463446c21bab0698bd8498b.
> Revert "test (#72)"

- src/main/kotlin/no/nav/syfo/api/endpoints/OppfolgingsoppgaveApi.kt
- src/main/kotlin/no/nav/syfo/application/OppfolgingsoppgaveService.kt
- src/main/kotlin/no/nav/syfo/domain/Oppfolgingsoppgave.kt
- src/test/kotlin/no/nav/syfo/application/OppfolgingsoppgaveServiceSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/api/OppfolgingsoppgaveApiSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/cronjob/PublishOppfolgingsoppgaveCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/infrastructure/OppfolgingsoppgaveRepositorySpek.kt
Fikser bug som gjorde at `createdBy` på oppfølgingsoppgave ikke ble endret når det ble laget en ny versjon av oppfølgingsoppgaven.
> IS-2665: Fix createdBy veileder bug

- src/main/kotlin/no/nav/syfo/domain/Oppfolgingsgrunn.kt
Har lagt til `brukermøte` som ny oppfølgingsgrunn. Det vil komme en relatert PR for syfomodiaperson.
> IS-2891: Lagt til brukermøte som ny oppfølgingsgrunn

- build.gradle.kts
- src/main/kotlin/no/nav/syfo/App.kt
- src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt
- src/test/kotlin/no/nav/syfo/huskelapp/api/OppfolgingsoppgaveApiSpek.kt
Basert på https://github.com/navikt/ishuskelapp/pull/86 så avventer merge til den er merget
> IS-2720: Ktor3

- src/main/kotlin/no/nav/syfo/infrastructure/database/repository/OppfolgingsoppgaveRepository.kt
- src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
- src/main/resources/db/migration/V2_0__add_view.sql
Det er et query som bruker *mye* CPU slik det er nå. Forsøker å optimalisere.
> IS-3033: Create view and optimize query

- src/main/kotlin/no/nav/syfo/infrastructure/cronjob/CronjobRunner.kt
Hva er nytt / hva har blitt fikset?
> IS-3033: Remove view and add validation
